### ISSUE TITLE
Redis not persistent

### ISSUE THREAD

**Issue by dadebulba** [marco-luzzara/telegram-bot-idrofobia#5]
The Redis used to store chatIds is not persistent.
In facts after 1 day the cache is empty and the game may crash.
Possible causes:
- it is shared with Directus and Directus writes into it
- the config for persistence is not taken correctly
- other causes, not clear

**Comment by marco-luzzara** [comment]
The bot cache was shared with Directus cache and they probably interfered with each other. Solved by keeping 2 distinct Redis cache instances, one for the bot and another one for directus. The docker-compose only instantiates the one of the bot.
