### ISSUE TITLE
Broadcast messaging tool

### ISSUE THREAD

**Issue by dadebulba** [marco-luzzara/telegram-bot-idrofobia#6]
Admin should be enabled to send a text message to every player via chatbot.
This will be useful for social/marketing purposes and broadcast communication interesting the game

**Comment by marco-luzzara** [comment]
should the messages be delivered to playing users only (those that are not dead) or to all of the users?

**Comment by dadebulba** [comment]
Can we set a flag? If only to active users or everyone?

**Comment by marco-luzzara** [comment]
Sure, you will choose it with a button if that's ok
